# Devin/legal/gdpr_compliance/data_mapping.py
# Purpose: Defines and manages a conceptual data map for GDPR compliance,
#          including records of processing activities (ROPA - Article 30).

import logging
import os
import sys
import uuid
from enum import Enum, auto
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Literal, Union, Set
from datetime import datetime

# Configure basic logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(name)s - %(message)s')
logger = logging.getLogger("GDPRDataMapping")

# --- Enums for Categorization ---

class DataCategory(Enum):
    """Categories of personal data processed."""
    USER_IDENTIFIERS = "User Identifiers & Authentication" # Usernames, passwords (hashed), user IDs, API keys
    CONTACT_INFORMATION = "Contact Information" # Email, phone number
    USER_PROFILE_PREFERENCES = "User Profile & Preferences" # Language, theme, custom settings
    USER_GENERATED_CONTENT_INPUT = "User-Generated Content & Inputs" # Prompts, code snippets, documents uploaded by user
    USER_GENERATED_CONTENT_OUTPUT = "AI-Generated Content & Outputs for User" # Code, text, images generated by Devin for the user
    USAGE_ANALYTICS_INTERACTION = "Usage Analytics & Interaction Data" # Features used, session duration, clicks, commands
    DEVICE_TECHNICAL_INFORMATION = "Device & Technical Information" # IP address, browser type, OS, device ID
    LOCATION_DATA = "Location Data" # If explicitly collected or inferred
    FINANCIAL_PAYMENT_INFORMATION = "Financial & Payment Information" # If Devin processes payments
    SUPPORT_COMMUNICATION = "Support & Communication Logs" # Chat logs with support, feedback
    THIRD_PARTY_INTEGRATION_DATA = "Third-Party Integration Data" # Data from connected services (e.g., GitHub, Jira)
    EMPLOYEE_CONTRACTOR_DATA = "Employee/Contractor Data" # If Devin also has internal users/admins
    MARKETING_PREFERENCES = "Marketing Preferences" # Opt-ins for newsletters, etc.
    LEGAL_CONSENT_RECORDS = "Legal & Consent Records" # Records of consent, ToS acceptance

class DataSensitivityLevel(Enum):
    """Sensitivity level of the data."""
    PUBLIC = auto()
    INTERNAL = auto() # General business data, not PII
    CONFIDENTIAL_PII = auto() # Standard PII
    HIGHLY_SENSITIVE_PII = auto() # Special categories of data (GDPR Art. 9), financial data
    STRICTLY_CONFIDENTIAL_SECRET = auto() # Trade secrets, critical credentials

class LegalBasisProcessing(Enum):
    """Legal basis for processing under GDPR Article 6."""
    CONSENT = "Consent (Art. 6(1)(a))"
    CONTRACT = "Performance of a Contract (Art. 6(1)(b))"
    LEGAL_OBLIGATION = "Compliance with a Legal Obligation (Art. 6(1)(c))"
    VITAL_INTERESTS = "Protection of Vital Interests (Art. 6(1)(d))"
    PUBLIC_TASK = "Performance of a Public Task (Art. 6(1)(e))"
    LEGITIMATE_INTERESTS = "Legitimate Interests (Art. 6(1)(f))"
    # For special category data (Art. 9)
    EXPLICIT_CONSENT_SPECIAL = "Explicit Consent for Special Category Data (Art. 9(2)(a))"
    EMPLOYMENT_SOCIAL_SECURITY_LAW = "Employment, Social Security, Social Protection Law (Art. 9(2)(b))"
    # ... other Art. 9 bases

class RecipientType(Enum):
    INTERNAL_TEAM = "Internal Team/System"
    THIRD_PARTY_PROCESSOR = "Third-Party Data Processor" # e.g., Cloud provider, LLM API provider
    JOINT_CONTROLLER = "Joint Controller"
    INDEPENDENT_CONTROLLER = "Independent Controller"
    LEGAL_AUTHORITY = "Legal/Regulatory Authority"

# --- Dataclasses for Data Map Elements ---

@dataclass
class DataElement:
    """Represents a specific piece of data being processed."""
    element_id: str # Unique identifier for this data element
    name: str # Human-readable name (e.g., "User Email Address")
    description: str
    categories: Set[DataCategory] # Can belong to multiple categories
    is_personal_data: bool # True if it's personal data under GDPR
    is_special_category_data: bool = False # GDPR Article 9 data
    sensitivity_level: DataSensitivityLevel = DataSensitivityLevel.CONFIDENTIAL_PII
    examples: List[str] = field(default_factory=list) # e.g., "john.doe@example.com"
    source_systems: List[str] = field(default_factory=list) # Systems where this data originates
    data_subject_types: List[str] = field(default_factory=list) # e.g., "Registered User", "Website Visitor"

@dataclass
class DataRecipient:
    """Represents an entity (internal or external) that receives data."""
    recipient_id: str
    name: str # e.g., "AWS S3 Storage", "OpenAI API", "Devin Analytics Team"
    recipient_type: RecipientType
    location: Optional[str] = None # Country or region, important for data transfers
    data_transfer_mechanism: Optional[str] = None # e.g., "SCCs", "BCRs", "Adequacy Decision" if outside EEA
    purpose_of_sharing: Optional[str] = None

@dataclass
class ProcessingActivity:
    """Represents a specific processing activity (ROPA entry)."""
    activity_id: str # Unique identifier for this activity
    name: str # e.g., "User Registration", "Task Execution Query to LLM"
    description: str
    department_owner: str # e.g., "Engineering", "Product", "Support"
    data_controller_details: str # Name and contact details of the controller (Devin company)
    dpo_contact_details: Optional[str] = None # Data Protection Officer contact

    purposes_of_processing: List[str]
    legal_bases_for_processing: Set[LegalBasisProcessing]
    data_subject_categories: Set[str] # e.g., "Registered Users", "Prospective Customers"
    
    # Link to DataElements by their element_id
    data_elements_processed_ids: Set[str] = field(default_factory=set)
    
    # Link to DataRecipients by their recipient_id
    data_recipients_ids: Set[str] = field(default_factory=set)
    
    # Data transfers outside EEA/UK
    transfers_to_third_country_or_international_org: bool = False
    third_country_or_org_name: Optional[str] = None
    safeguards_for_transfer: Optional[str] = None # e.g., SCCs, Adequacy Decision reference

    data_retention_period: str # e.g., "Session + 30 days", "7 years for financial records"
    technical_organizational_security_measures: List[str] = field(default_factory=list)
    
    data_protection_impact_assessment_conducted: bool = False # DPIA
    dpia_reference_or_date: Optional[str] = None

    last_reviewed_date: Optional[str] = None
    version: int = 1

class DevinDataMap:
    """
    Manages the collection of data elements and processing activities for Devin.
    This class serves as a conceptual in-memory store for the data map.
    In a real-world scenario, this data might be stored in a database,
    a dedicated GDPR compliance tool, or version-controlled structured files (JSON/YAML).
    """

    def __init__(self):
        self.data_elements: Dict[str, DataElement] = {}
        self.data_recipients: Dict[str, DataRecipient] = {}
        self.processing_activities: Dict[str, ProcessingActivity] = {}
        
        self._load_all_definitions()
        logger.info("DevinDataMap initialized with conceptual data elements and processing activities.")

    def _add_data_element(self, de: DataElement):
        if de.element_id in self.data_elements:
            logger.warning(f"DataElement with ID '{de.element_id}' already exists. Overwriting.")
        self.data_elements[de.element_id] = de
        
    def _add_data_recipient(self, dr: DataRecipient):
        if dr.recipient_id in self.data_recipients:
            logger.warning(f"DataRecipient with ID '{dr.recipient_id}' already exists. Overwriting.")
        self.data_recipients[dr.recipient_id] = dr

    def _add_processing_activity(self, pa: ProcessingActivity):
        # Validate that referenced data_elements and recipients exist
        for de_id in pa.data_elements_processed_ids:
            if de_id not in self.data_elements:
                raise ValueError(f"ProcessingActivity '{pa.activity_id}' references non-existent DataElement ID '{de_id}'. Define DataElements first.")
        for dr_id in pa.data_recipients_ids:
            if dr_id not in self.data_recipients:
                 raise ValueError(f"ProcessingActivity '{pa.activity_id}' references non-existent DataRecipient ID '{dr_id}'. Define DataRecipients first.")

        if pa.activity_id in self.processing_activities:
            logger.warning(f"ProcessingActivity with ID '{pa.activity_id}' already exists. Overwriting.")
        self.processing_activities[pa.activity_id] = pa

    def _load_all_definitions(self):
        """Loads all predefined data elements, recipients, and processing activities."""
        self._define_data_elements()
        self._define_data_recipients()
        # _define_processing_activities will be in Part 2
        # self._define_processing_activities() # Call this after elements & recipients are defined

    def _define_data_elements(self):
        """
        Defines the various data elements Devin processes.
        This is a conceptual list and needs to be meticulously maintained and verified
        against actual data flows in the Devin application.
        """
        elements = [
            # User Identifiers & Authentication
            DataElement(element_id="DE001", name="User ID", description="Unique identifier for a Devin user.",
                        categories={DataCategory.USER_IDENTIFIERS}, is_personal_data=True,
                        sensitivity_level=DataSensitivityLevel.CONFIDENTIAL_PII, examples=["user_12345abc"],
                        source_systems=["Devin Auth Service", "User Database"], data_subject_types=["Registered User"]),
            DataElement(element_id="DE002", name="Username/Login Handle", description="User-chosen or assigned username.",
                        categories={DataCategory.USER_IDENTIFIERS}, is_personal_data=True,
                        sensitivity_level=DataSensitivityLevel.CONFIDENTIAL_PII, examples=["john_doe", "devin_master"],
                        source_systems=["User Input", "Devin Auth Service"], data_subject_types=["Registered User"]),
            DataElement(element_id="DE003", name="Hashed Password", description="User's password, hashed and salted.",
                        categories={DataCategory.USER_IDENTIFIERS}, is_personal_data=True, # Still PII even if hashed
                        sensitivity_level=DataSensitivityLevel.HIGHLY_SENSITIVE_PII, examples=["$2b$12$.... (bcrypt hash)"],
                        source_systems=["Devin Auth Service"], data_subject_types=["Registered User"]),
            DataElement(element_id="DE004", name="Authentication Tokens", description="OAuth tokens, session cookies, API keys.",
                        categories={DataCategory.USER_IDENTIFIERS}, is_personal_data=True,
                        sensitivity_level=DataSensitivityLevel.HIGHLY_SENSITIVE_PII, examples=["jwt_token_string", "session_id_abc"],
                        source_systems=["Devin Auth Service", "Browser Storage"], data_subject_types=["Registered User", "API User"]),
            
            # Contact Information
            DataElement(element_id="DE005", name="Email Address", description="User's email address.",
                        categories={DataCategory.CONTACT_INFORMATION, DataCategory.USER_IDENTIFIERS}, is_personal_data=True,
                        sensitivity_level=DataSensitivityLevel.CONFIDENTIAL_PII, examples=["jane.doe@example.com"],
                        source_systems=["User Input", "SSO Provider"], data_subject_types=["Registered User", "Support Requester"]),
            DataElement(element_id="DE006", name="Phone Number", description="User's phone number (optional).",
                        categories={DataCategory.CONTACT_INFORMATION}, is_personal_data=True,
                        sensitivity_level=DataSensitivityLevel.CONFIDENTIAL_PII, examples=["+1-555-123-4567"],
                        source_systems=["User Input"], data_subject_types=["Registered User"]),

            # User Profile & Preferences
            DataElement(element_id="DE007", name="Display Name", description="User's chosen display name.",
                        categories={DataCategory.USER_PROFILE_PREFERENCES}, is_personal_data=True,
                        sensitivity_level=DataSensitivityLevel.CONFIDENTIAL_PII, examples=["Jane D."],
                        source_systems=["User Input"], data_subject_types=["Registered User"]),
            DataElement(element_id="DE008", name="User Preferences", description="Application settings, language, theme, notification settings.",
                        categories={DataCategory.USER_PROFILE_PREFERENCES}, is_personal_data=False, # Generally false unless preferences themselves reveal PII
                        sensitivity_level=DataSensitivityLevel.INTERNAL, examples=["{'theme':'dark', 'lang':'en'}"],
                        source_systems=["User Input", "Application"], data_subject_types=["Registered User"]),
            
            # User Generated Content & Inputs
            DataElement(element_id="DE009", name="User Prompts & Queries", description="Text, voice, or other inputs provided by the user to Devin.",
                        categories={DataCategory.USER_GENERATED_CONTENT_INPUT}, is_personal_data=True, # Can contain PII
                        sensitivity_level=DataSensitivityLevel.CONFIDENTIAL_PII, # Could be higher if sensitive topics discussed
                        examples=["'Write python code for a web scraper'", "Uploaded_specification.docx content"],
                        source_systems=["User Interface", "API Input"], data_subject_types=["Registered User"]),
            DataElement(element_id="DE010", name="Uploaded Files/Code by User", description="Files, code snippets, or data uploaded by the user.",
                        categories={DataCategory.USER_GENERATED_CONTENT_INPUT}, is_personal_data=True, # Depending on content
                        sensitivity_level=DataSensitivityLevel.HIGHLY_SENSITIVE_PII, # Depending on content
                        examples=["my_project_code.zip", "financial_data.csv (if uploaded by user)"],
                        source_systems=["User Interface Upload"], data_subject_types=["Registered User"]),

            # AI-Generated Content & Outputs for User
            DataElement(element_id="DE011", name="Generated Code/Text by Devin", description="Code, text, summaries, or other content generated by Devin based on user input.",
                        categories={DataCategory.USER_GENERATED_CONTENT_OUTPUT}, is_personal_data=False, # Generally, unless it incorporates user's PII from input
                        sensitivity_level=DataSensitivityLevel.INTERNAL, # Can become PII if user input had PII
                        examples=["def hello(): print('Hello')"],
                        source_systems=["Devin AI Core"], data_subject_types=["Registered User"]),
            DataElement(element_id="DE012", name="Devin Action Logs/Execution Traces", description="Logs of actions Devin takes on behalf of the user (e.g., files created, commands run).",
                        categories={DataCategory.USER_GENERATED_CONTENT_OUTPUT, DataCategory.USAGE_ANALYTICS_INTERACTION}, is_personal_data=True,
                        sensitivity_level=DataSensitivityLevel.CONFIDENTIAL_PII,
                        examples=["Created file /tmp/user_code/script.py", "Executed 'git commit'"],
                        source_systems=["Devin Agent Execution Environment"], data_subject_types=["Registered User"]),

            # Usage Analytics & Interaction Data
            DataElement(element_id="DE013", name="IP Address", description="IP address of the user connecting to Devin.",
                        categories={DataCategory.DEVICE_TECHNICAL_INFORMATION, DataCategory.USAGE_ANALYTICS_INTERACTION}, is_personal_data=True,
                        sensitivity_level=DataSensitivityLevel.CONFIDENTIAL_PII, examples=["192.168.1.100", "2001:db8::1"],
                        source_systems=["Web Server Logs", "Application Server"], data_subject_types=["Registered User", "Website Visitor"]),
            DataElement(element_id="DE014", name="User-Agent String", description="Browser/client user-agent information.",
                        categories={DataCategory.DEVICE_TECHNICAL_INFORMATION}, is_personal_data=True, # Can contribute to fingerprinting
                        sensitivity_level=DataSensitivityLevel.CONFIDENTIAL_PII, examples=["Mozilla/5.0 (...) Chrome/90.0"],
                        source_systems=["Web Server Logs"], data_subject_types=["Registered User", "Website Visitor"]),
            DataElement(element_id="DE015", name="Interaction Timestamps & Events", description="Timestamps of login, logout, feature usage, button clicks.",
                        categories={DataCategory.USAGE_ANALYTICS_INTERACTION}, is_personal_data=True, # When linked to a user ID
                        sensitivity_level=DataSensitivityLevel.CONFIDENTIAL_PII, examples=["'login_success': '2025-05-21T15:30:00Z'"],
                        source_systems=["Application Logs", "Analytics Service"], data_subject_types=["Registered User"]),
            DataElement(element_id="DE016", name="Session ID", description="Identifier for a user's session.",
                        categories={DataCategory.USAGE_ANALYTICS_INTERACTION, DataCategory.USER_IDENTIFIERS}, is_personal_data=True,
                        sensitivity_level=DataSensitivityLevel.CONFIDENTIAL_PII, examples=["session_xyz789"],
                        source_systems=["Application Server", "Web Server"], data_subject_types=["Registered User", "Website Visitor"]),

            # Third-Party Integration Data
            DataElement(element_id="DE017", name="Third-Party Service Tokens", description="Access/refresh tokens for integrated services like GitHub, Jira, cloud providers.",
                        categories={DataCategory.THIRD_PARTY_INTEGRATION_DATA, DataCategory.USER_IDENTIFIERS}, is_personal_data=True,
                        sensitivity_level=DataSensitivityLevel.HIGHLY_SENSITIVE_PII, examples=["github_oauth_token_xxx"],
                        source_systems=["User Input (OAuth flow)", "Devin Integration Manager"], data_subject_types=["Registered User"]),
            DataElement(element_id="DE018", name="Data Retrieved from Third-Party Services", description="Content retrieved from integrated services (e.g., repo file list, issue details).",
                        categories={DataCategory.THIRD_PARTY_INTEGRATION_DATA}, is_personal_data=True, # Can contain PII from that service
                        sensitivity_level=DataSensitivityLevel.CONFIDENTIAL_PII, # Depends on the data source
                        examples=["List of files in a GitHub repo", "Jira issue description"],
                        source_systems=["External APIs (GitHub, Jira, etc.)"], data_subject_types=["Registered User"]),
            
            # Legal & Consent Records
            DataElement(element_id="DE019", name="Consent Records", description="Records of user consent for specific processing activities (e.g., marketing, cookie consent).",
                        categories={DataCategory.LEGAL_CONSENT_RECORDS}, is_personal_data=True,
                        sensitivity_level=DataSensitivityLevel.CONFIDENTIAL_PII, examples=["User 'user_123' consented to 'marketing_emails' on 2025-01-15."],
                        source_systems=["Consent Management Platform", "Application Database"], data_subject_types=["Registered User", "Website Visitor"]),
            DataElement(element_id="DE020", name="Terms of Service Acceptance", description="Record of user accepting ToS.",
                        categories={DataCategory.LEGAL_CONSENT_RECORDS}, is_personal_data=True,
                        sensitivity_level=DataSensitivityLevel.CONFIDENTIAL_PII, examples=["User 'user_123' accepted ToS version 3.1 on 2025-01-10."],
                        source_systems=["Application Database"], data_subject_types=["Registered User"]),

            # Financial (If applicable)
            # DataElement(element_id="DE021", name="Credit Card Details (Partial/Tokenized)", ...),
            # DataElement(element_id="DE022", name="Billing Address", ...),

            # Support Communications
            DataElement(element_id="DE023", name="Support Ticket Content", description="User's messages and attachments submitted via support channels.",
                        categories={DataCategory.SUPPORT_COMMUNICATION}, is_personal_data=True, # Can contain any PII user provides
                        sensitivity_level=DataSensitivityLevel.CONFIDENTIAL_PII,
                        source_systems=["Support System (e.g., Zendesk, Intercom)", "Email"], data_subject_types=["Registered User", "Support Requester"]),
        ]
        for el in elements:
            self._add_data_element(el)
        logger.info(f"Defined {len(self.data_elements)} conceptual data elements.")

    def _define_data_recipients(self):
        """Defines potential recipients of data."""
        recipients = [
            # Internal
            DataRecipient(recipient_id="DR001", name="Devin Primary Application Database", recipient_type=RecipientType.INTERNAL_TEAM, location="Cloud Region (e.g., US-East-1)", purpose_of_sharing="Core application functionality, data persistence."),
            DataRecipient(recipient_id="DR002", name="Devin Log Aggregation System (Loki)", recipient_type=RecipientType.INTERNAL_TEAM, location="Cloud Region", purpose_of_sharing="Troubleshooting, monitoring, security auditing."),
            DataRecipient(recipient_id="DR003", name="Devin Analytics Platform", recipient_type=RecipientType.INTERNAL_TEAM, location="Cloud Region", purpose_of_sharing="Product improvement, usage analysis (aggregated/anonymized where possible)."),
            DataRecipient(recipient_id="DR004", name="Devin Customer Support Team", recipient_type=RecipientType.INTERNAL_TEAM, location="Global", purpose_of_sharing="Providing user support, resolving issues."),

            # Third-Party Processors (Examples - specific ones depend on Devin's stack)
            DataRecipient(recipient_id="DR005", name="Cloud Hosting Provider (e.g., AWS, GCP, Azure)", recipient_type=RecipientType.THIRD_PARTY_PROCESSOR, location="Configurable Cloud Regions", data_transfer_mechanism="SCCs/BCRs/Adequacy", purpose_of_sharing="Infrastructure hosting (compute, storage, networking)."),
            DataRecipient(recipient_id="DR006", name="LLM API Provider (e.g., OpenAI, Anthropic)", recipient_type=RecipientType.THIRD_PARTY_PROCESSOR, location="Primarily USA (check provider specifics)", data_transfer_mechanism="SCCs/DPA", purpose_of_sharing="Core AI text/code generation capabilities."),
            DataRecipient(recipient_id="DR007", name="Payment Processor (e.g., Stripe, PayPal)", recipient_type=RecipientType.THIRD_PARTY_PROCESSOR, location="Global/USA", data_transfer_mechanism="SCCs/BCRs/PCI-DSS", purpose_of_sharing="Processing subscription payments (if applicable)."),
            DataRecipient(recipient_id="DR008", name="Email Service Provider (e.g., SendGrid, Mailgun)", recipient_type=RecipientType.THIRD_PARTY_PROCESSOR, location="USA/Global", data_transfer_mechanism="SCCs/DPA", purpose_of_sharing="Sending transactional and marketing emails."),
            DataRecipient(recipient_id="DR009", name="Customer Support Platform (e.g., Zendesk)", recipient_type=RecipientType.THIRD_PARTY_PROCESSOR, location="USA/Global", data_transfer_mechanism="SCCs/DPA", purpose_of_sharing="Managing customer support interactions."),
            DataRecipient(recipient_id="DR010", name="Analytics Service (e.g., Mixpanel, Google Analytics)", recipient_type=RecipientType.THIRD_PARTY_PROCESSOR, location="USA/Global", data_transfer_mechanism="SCCs/DPA", purpose_of_sharing="Tracking user behavior for product improvement.")
        ]
        for dr in recipients:
            self._add_data_recipient(dr)
        logger.info(f"Defined {len(self.data_recipients)} conceptual data recipients.")

import logging
import os
import sys
import uuid
from enum import Enum, auto
from dataclasses import dataclass, field, asdict # Import asdict
from typing import Dict, List, Optional, Literal, Union, Set
from datetime import datetime

# --- Enums, Dataclasses, and Logger (assume they are defined as in Part 1) ---
# (For brevity, I won't repeat them here, but they are part of the same file)
# DataCategory, DataSensitivityLevel, LegalBasisProcessing, RecipientType
# DataElement, DataRecipient, ProcessingActivity

# Logger (from Part 1)
logger = logging.getLogger("GDPRDataMapping")

class DevinDataMap:
    # (Assume __init__, _add_data_element, _add_data_recipient, _add_processing_activity,
    #  _define_data_elements, _define_data_recipients from Part 1 are here)

    def _load_all_definitions(self):
        """Loads all predefined data elements, recipients, and processing activities."""
        self._define_data_elements() # From Part 1
        self._define_data_recipients() # From Part 1
        self._define_processing_activities() # Defined in this part
        logger.info(f"DevinDataMap fully loaded: {len(self.data_elements)} elements, {len(self.data_recipients)} recipients, {len(self.processing_activities)} activities.")


    def _define_processing_activities(self):
        """
        Defines the various processing activities undertaken by Devin.
        Each activity should link to defined DataElements and DataRecipients by their IDs.
        This is a conceptual list and needs meticulous, ongoing verification.
        """
        activities = [
            ProcessingActivity(
                activity_id="PA001", name="User Account Registration",
                description="Collection and storage of user information to create and manage their Devin account.",
                department_owner="Engineering/Product",
                data_controller_details="Devin Corp, 123 AI Lane, Tech City, contact@devin.ai",
                dpo_contact_details="dpo@devin.ai (if applicable)",
                purposes_of_processing=["To provide user access to Devin services", "Account management and security", "Communication regarding the account"],
                legal_bases_for_processing={LegalBasisProcessing.CONTRACT, LegalBasisProcessing.LEGITIMATE_INTERESTS},
                data_subject_categories={"Registered Users", "Prospective Users"},
                data_elements_processed_ids={"DE001", "DE002", "DE003", "DE005", "DE007", "DE013", "DE014", "DE020"}, # UserID, Username, HashedPass, Email, DisplayName, IP, UserAgent, ToS
                data_recipients_ids={"DR001", "DR002", "DR005", "DR008"}, # PrimaryDB, Loki, CloudHost, EmailProvider (for welcome email)
                data_retention_period="Duration of account activity + 3 years for legal claims (or as per policy). Login credentials until account deletion.",
                technical_organizational_security_measures=["Password hashing (bcrypt/scrypt)", "HTTPS/TLS for data in transit", "Role-based access control (RBAC)", "Regular security patching", "Data backup and recovery procedures"],
                last_reviewed_date=datetime.now().strftime("%Y-%m-%d")
            ),
            ProcessingActivity(
                activity_id="PA002", name="User Authentication & Session Management",
                description="Verifying user identity and managing user sessions for secure access.",
                department_owner="Engineering",
                data_controller_details="Devin Corp, 123 AI Lane, Tech City, contact@devin.ai",
                purposes_of_processing=["Securely authenticate users", "Maintain user sessions", "Prevent unauthorized access"],
                legal_bases_for_processing={LegalBasisProcessing.CONTRACT, LegalBasisProcessing.LEGITIMATE_INTERESTS},
                data_subject_categories={"Registered Users"},
                data_elements_processed_ids={"DE001", "DE002", "DE003", "DE004", "DE013", "DE016"}, # UserID, Username, HashedPass, AuthTokens, IP, SessionID
                data_recipients_ids={"DR001", "DR002", "DR005"}, # PrimaryDB, Loki, CloudHost
                data_retention_period="Auth tokens: Session duration or token expiry. Session logs: 90 days.",
                technical_organizational_security_measures=["Secure token generation & storage", "HTTPS/TLS", "Brute-force protection", "Session timeout policies"],
                last_reviewed_date=datetime.now().strftime("%Y-%m-%d")
            ),
            ProcessingActivity(
                activity_id="PA003", name="Processing User Prompts with LLM",
                description="Sending user prompts/queries and relevant context to an LLM API to generate responses (code, text, etc.).",
                department_owner="AI/ML Engineering",
                data_controller_details="Devin Corp, 123 AI Lane, Tech City, contact@devin.ai",
                purposes_of_processing=["To fulfill user requests for AI-generated content/actions", "To provide core Devin AI functionality"],
                legal_bases_for_processing={LegalBasisProcessing.CONTRACT}, # User requests service
                data_subject_categories={"Registered Users"},
                data_elements_processed_ids={"DE001", "DE009", "DE010", "DE018"}, # UserID (for context/history if used), UserPrompts, UploadedFiles, DataFrom3rdParty (if context)
                data_recipients_ids={"DR006", "DR002", "DR005"}, # LLM API Provider, Loki (for request/response logging), CloudHost (for processing)
                transfers_to_third_country_or_international_org=True, # LLM provider might be in US
                third_country_or_org_name="LLM API Provider (e.g., USA)",
                safeguards_for_transfer="Standard Contractual Clauses (SCCs), Data Processing Addendum (DPA) with provider, assessment of provider's security.",
                data_retention_period="Prompts and immediate LLM responses: As per user session or short-term for context, unless explicitly saved by user. Logs: 90 days.",
                technical_organizational_security_measures=["API key security", "Data minimization in prompts where possible", "Review of LLM provider's data handling policies", "HTTPS/TLS for API calls"],
                data_protection_impact_assessment_conducted=True, # Likely for LLM usage
                dpia_reference_or_date="DPIA_LLM_Usage_v1_" + datetime.now().strftime("%Y%m%d"),
                last_reviewed_date=datetime.now().strftime("%Y-%m-%d")
            ),
            ProcessingActivity(
                activity_id="PA004", name="Storing User-Generated Content",
                description="Storing content actively created or saved by the user within Devin (e.g., project files, notes, saved AI outputs).",
                department_owner="Engineering/Product",
                data_controller_details="Devin Corp, 123 AI Lane, Tech City, contact@devin.ai",
                purposes_of_processing=["To allow users to persist their work", "To enable project continuity and collaboration (if applicable)"],
                legal_bases_for_processing={LegalBasisProcessing.CONTRACT},
                data_subject_categories={"Registered Users"},
                data_elements_processed_ids={"DE001", "DE009", "DE010", "DE011", "DE012"}, # UserID, Prompts(if saved), UploadedFiles, GeneratedContent(if saved), ActionLogs(if represent state)
                data_recipients_ids={"DR001", "DR005"}, # PrimaryDB/ObjectStorage, CloudHost
                data_retention_period="As long as the user account is active and content is not deleted by user, or per data lifecycle policy.",
                technical_organizational_security_measures=["Encryption at rest (AES-256)", "Encryption in transit (HTTPS/TLS)", "Access controls", "Regular backups"],
                last_reviewed_date=datetime.now().strftime("%Y-%m-%d")
            ),
            ProcessingActivity(
                activity_id="PA005", name="Service Usage Analytics & Monitoring",
                description="Collecting and analyzing data about how users interact with Devin for service improvement, troubleshooting, and security monitoring.",
                department_owner="Product/Engineering/Security",
                data_controller_details="Devin Corp, 123 AI Lane, Tech City, contact@devin.ai",
                purposes_of_processing=["To understand service usage patterns", "To identify popular features and areas for improvement", "To detect and prevent fraudulent or abusive activity", "To monitor system performance and stability"],
                legal_bases_for_processing={LegalBasisProcessing.LEGITIMATE_INTERESTS, LegalBasisProcessing.CONTRACT # (for service operation logs)
                                           },
                data_subject_categories={"Registered Users", "Website Visitors"},
                data_elements_processed_ids={"DE001", "DE013", "DE014", "DE015", "DE016", "DE008"}, # UserID, IP, UserAgent, InteractionEvents, SessionID, UserPreferences (for feature usage)
                data_recipients_ids={"DR002", "DR003", "DR005", "DR010"}, # Loki, AnalyticsPlatform, CloudHost, AnalyticsService (3rd party)
                data_retention_period="Aggregated analytics: Indefinitely (anonymized/pseudonymized). Raw interaction logs: 90-180 days.",
                technical_organizational_security_measures=["Pseudonymization/anonymization where possible for analytics", "Data minimization", "Secure storage and access controls for logs", "Regular review of analytics data for PII leakage"],
                last_reviewed_date=datetime.now().strftime("%Y-%m-%d")
            ),
             ProcessingActivity(
                activity_id="PA006", name="Customer Support Management",
                description="Processing user data to provide customer support and resolve issues.",
                department_owner="Support",
                data_controller_details="Devin Corp, 123 AI Lane, Tech City, contact@devin.ai",
                purposes_of_processing=["To respond to user inquiries", "To troubleshoot problems", "To improve customer service"],
                legal_bases_for_processing={LegalBasisProcessing.CONTRACT, LegalBasisProcessing.LEGITIMATE_INTERESTS},
                data_subject_categories={"Registered Users", "Support Requesters"},
                data_elements_processed_ids={"DE001", "DE005", "DE006", "DE009", "DE012", "DE015", "DE023"}, # UserID, Email, Phone, Prompts(if relevant), ActionLogs, InteractionEvents, SupportTicketContent
                data_recipients_ids={"DR004", "DR009", "DR002"}, # SupportTeam, SupportPlatform, Loki (for audit)
                data_retention_period="Support tickets: 2 years after resolution, or as per legal requirements.",
                technical_organizational_security_measures=["Access controls for support platform", "Secure communication channels", "Training for support staff on data privacy"],
                last_reviewed_date=datetime.now().strftime("%Y-%m-%d")
            ),
            # Add more activities: Third-party integrations, marketing, backups, etc.
        ]
        for act in activities:
            self._add_processing_activity(act)
        logger.info(f"Defined {len(self.processing_activities)} conceptual processing activities.")

    # --- Getter Methods ---
    def get_data_element_by_id(self, element_id: str) -> Optional[DataElement]:
        return self.data_elements.get(element_id)

    def get_data_recipient_by_id(self, recipient_id: str) -> Optional[DataRecipient]:
        return self.data_recipients.get(recipient_id)

    def get_processing_activity_by_id(self, activity_id: str) -> Optional[ProcessingActivity]:
        return self.processing_activities.get(activity_id)

    # --- Query and Reporting Methods ---
    def find_activities_using_data_element(self, element_id: str) -> List[ProcessingActivity]:
        """Finds all processing activities that involve a specific data element."""
        if element_id not in self.data_elements:
            logger.warning(f"Data element ID '{element_id}' not found in the map.")
            return []
        return [
            activity for activity in self.processing_activities.values()
            if element_id in activity.data_elements_processed_ids
        ]

    def find_elements_in_activity(self, activity_id: str) -> List[DataElement]:
        """Finds all data elements involved in a specific processing activity."""
        activity = self.get_processing_activity_by_id(activity_id)
        if not activity:
            logger.warning(f"Processing activity ID '{activity_id}' not found.")
            return []
        return [self.data_elements[el_id] for el_id in activity.data_elements_processed_ids if el_id in self.data_elements]

    def generate_ropa_summary_text(self, activity_id: Optional[str] = None) -> str:
        """
        Generates a textual summary for one or all processing activities,
        suitable for inclusion in a Record of Processing Activities (ROPA) document.
        """
        report_lines = ["="*30 + " Record of Processing Activities (ROPA) Summary " + "="*30]

        activities_to_report = []
        if activity_id:
            activity = self.get_processing_activity_by_id(activity_id)
            if activity:
                activities_to_report.append(activity)
            else:
                return f"No processing activity found with ID: {activity_id}"
        else:
            activities_to_report = list(self.processing_activities.values())
            report_lines.append(f"Summary for all {len(activities_to_report)} processing activities.")

        if not activities_to_report:
            return "No processing activities to report on."

        for i, activity in enumerate(activities_to_report):
            report_lines.append(f"\n--- Activity {i+1}: {activity.name} (ID: {activity.activity_id}) ---")
            report_lines.append(f"  Description: {activity.description}")
            report_lines.append(f"  Owner Department: {activity.department_owner}")
            report_lines.append(f"  Controller: {activity.data_controller_details}")
            if activity.dpo_contact_details:
                report_lines.append(f"  DPO Contact: {activity.dpo_contact_details}")
            report_lines.append(f"  Purposes: {'; '.join(activity.purposes_of_processing)}")
            report_lines.append(f"  Legal Bases: {', '.join(lb.value for lb in activity.legal_bases_for_processing)}")
            report_lines.append(f"  Data Subject Categories: {', '.join(activity.data_subject_categories)}")
            
            report_lines.append("  Data Elements Processed:")
            for el_id in activity.data_elements_processed_ids:
                element = self.get_data_element_by_id(el_id)
                if element:
                    report_lines.append(f"    - {element.name} (ID: {el_id}, Categories: {[cat.name for cat in element.categories]}, PII: {element.is_personal_data}, Sensitivity: {element.sensitivity_level.name})")
            
            report_lines.append("  Data Recipients:")
            for rec_id in activity.data_recipients_ids:
                recipient = self.get_data_recipient_by_id(rec_id)
                if recipient:
                    report_lines.append(f"    - {recipient.name} (ID: {rec_id}, Type: {recipient.recipient_type.name}, Location: {recipient.location or 'N/A'})")

            if activity.transfers_to_third_country_or_international_org:
                report_lines.append(f"  International Transfer: Yes, to {activity.third_country_or_org_name or 'unspecified'}")
                report_lines.append(f"    Safeguards: {activity.safeguards_for_transfer or 'Not specified'}")
            else:
                report_lines.append("  International Transfer: No")

            report_lines.append(f"  Retention Period: {activity.data_retention_period}")
            report_lines.append(f"  Security Measures: {'; '.join(activity.technical_organizational_security_measures) if activity.technical_organizational_security_measures else 'Not specified'}")
            
            report_lines.append(f"  DPIA Conducted: {'Yes' if activity.data_protection_impact_assessment_conducted else 'No'}")
            if activity.data_protection_impact_assessment_conducted and activity.dpia_reference_or_date:
                report_lines.append(f"    DPIA Reference: {activity.dpia_reference_or_date}")
            report_lines.append(f"  Last Reviewed: {activity.last_reviewed_date or 'N/A'}, Version: {activity.version}")

        return "\n".join(report_lines)

    def export_map_as_dict(self) -> Dict[str, Any]:
        """Exports the entire data map as a structured dictionary."""
        return {
            "data_elements": {el_id: asdict(el) for el_id, el in self.data_elements.items()},
            "data_recipients": {rec_id: asdict(rec) for rec_id, rec in self.data_recipients.items()},
            "processing_activities": {act_id: asdict(act) for act_id, act in self.processing_activities.items()}
        }

# Example Usage (conceptual)
if __name__ == "__main__":
    print("=========================================================")
    print("=== Running GDPR Data Mapping Prototype ===")
    print("=========================================================")

    # Initialize the data map (loads predefined elements, recipients, and activities)
    devin_data_map = DevinDataMap()

    print(f"\nTotal Data Elements Defined: {len(devin_data_map.data_elements)}")
    print(f"Total Data Recipients Defined: {len(devin_data_map.data_recipients)}")
    print(f"Total Processing Activities Defined: {len(devin_data_map.processing_activities)}")

    # --- Example: Find activities using a specific data element ---
    email_element_id = "DE005" # User Email Address
    activities_with_email = devin_data_map.find_activities_using_data_element(email_element_id)
    print(f"\n--- Processing Activities involving Data Element '{devin_data_map.get_data_element_by_id(email_element_id).name if devin_data_map.get_data_element_by_id(email_element_id) else email_element_id}': ---")
    if activities_with_email:
        for activity in activities_with_email:
            print(f"  - Activity: {activity.name} (ID: {activity.activity_id})")
    else:
        print("  No activities found for this data element.")

    # --- Example: Find elements in a specific activity ---
    llm_activity_id = "PA003" # Processing User Prompts with LLM
    elements_in_llm_activity = devin_data_map.find_elements_in_activity(llm_activity_id)
    print(f"\n--- Data Elements involved in Activity '{devin_data_map.get_processing_activity_by_id(llm_activity_id).name if devin_data_map.get_processing_activity_by_id(llm_activity_id) else llm_activity_id}': ---")
    if elements_in_llm_activity:
        for element in elements_in_llm_activity:
            print(f"  - Element: {element.name} (ID: {element.element_id})")
    else:
        print("  No elements found or activity ID is invalid.")


    # --- Example: Generate ROPA summary for a specific activity ---
    print("\n--- ROPA Summary for 'User Account Registration' (PA001) ---")
    ropa_summary_single = devin_data_map.generate_ropa_summary_text(activity_id="PA001")
    print(ropa_summary_single)

    # --- Example: Generate full ROPA summary (first few lines) ---
    # print("\n--- Full ROPA Summary (Excerpt) ---")
    # full_ropa_summary = devin_data_map.generate_ropa_summary_text()
    # print("\n".join(full_ropa_summary.splitlines()[:50])) # Print first 50 lines

    # --- Example: Export the entire map as a dictionary (print a part of it) ---
    # This could be saved to JSON/YAML file for documentation or version control
    # For example:
    # if yaml:
    #     with open("devin_data_map_export.yaml", "w") as f:
    #         yaml.dump(devin_data_map.export_map_as_dict(), f, indent=2, sort_keys=False, Dumper=yaml.SafeDumper)
    #     logger.info("Full data map exported to devin_data_map_export.yaml")
    # else:
    #     logger.warning("PyYAML not available, cannot export to YAML file. Printing snippet.")
    #     map_dict = devin_data_map.export_map_as_dict()
    #     print("\n--- Exported Data Map Snippet (Processing Activities) ---")
    #     print(json.dumps(list(map_dict["processing_activities"].items())[:1], indent=2, default=str))


    logger.info("\nThis data map is a conceptual representation and requires continuous, "
                "meticulous review and updates to reflect actual data processing practices "
                "within the Devin application for GDPR compliance.")

    print("\n=========================================================")
    print("=== GDPR Data Mapping Prototype Complete ===")
    print("=========================================================")
