# Devin/threat_intel/cognitive/threat_analyzer.py
# Purpose: An AI-powered tool to analyze text for signs of sophisticated,
#          AI-generated phishing and social engineering from a defensive perspective.

import logging
import json
from dataclasses import dataclass, field
from typing import List, Optional, Dict, Any

# --- CRITICAL SAFETY AND LEGAL NOTE ---
# This module is designed for DEFENSIVE security analysis of text to DETECT
# potential social engineering attacks. It does NOT generate any malicious
# or deceptive content.
# ----------------------------------------

try:
    from modules.all_ais_modules import AIAgent, AIProvider
    DEVIN_CORE_AVAILABLE = True
except ImportError as e:
    DEVIN_CORE_AVAILABLE = False
    _import_error = e

# Configure basic logging
logger = logging.getLogger("AIThreatAnalyzer")
if not logger.handlers:
    h = logging.StreamHandler()
    h.setFormatter(logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s'))
    logger.addHandler(h)
    logger.setLevel(logging.INFO)

@dataclass
class PhishingAnalysisReport:
    """A structured report of a phishing analysis."""
    risk_score: float
    recommendation: str # e.g., "QUARANTINE", "USER_CAUTION", "SAFE"
    red_flags: List[str]
    summary: str

class AIThreatAnalyzer:
    """Uses an LLM to perform threat analysis on text for social engineering."""
    def __init__(self, ai_agent: AIAgent):
        if not DEVIN_CORE_AVAILABLE:
            raise ImportError(f"A core Devin module is missing. Error: {_import_error}")
        self.agent = ai_agent

    def analyze_text_for_phishing(self, email_body: str, sender: str) -> Optional[PhishingAnalysisReport]:
        """Analyzes an email's content for signs of AI-powered phishing."""
        logger.info("Analyzing email text for signs of phishing...")
        prompt = (
            "You are a senior cybersecurity analyst specializing in detecting AI-generated phishing and social engineering attacks. "
            "Analyze the following email content and sender information. Look for red flags such as: manufactured urgency, unusual grammar or phrasing, "
            "suspicious links, requests for sensitive information, and mismatched sender information. Pay special attention to "
            "deceptive tactics that might be generated by a sophisticated AI.\n\n"
            "Respond ONLY with a single, valid JSON object with the following keys:\n"
            "- \"risk_score\": A float from 0.0 (perfectly safe) to 1.0 (certainly malicious).\n"
            "- \"recommendation\": Your final verdict. One of [\"SAFE\", \"USER_CAUTION\", \"QUARANTINE\"].\n"
            "- \"red_flags\": A list of strings, where each string is a specific red flag you identified.\n"
            "- \"summary\": A one-sentence summary of your findings.\n\n"
            f"--- EMAIL TO ANALYZE ---\nSender: {sender}\nBody:\n{email_body}\n--- END OF EMAIL ---"
        )
        
        try:
            response_str = self.agent.get_general_chat_response([{"role": "user", "content": prompt}], AIProvider.OPENAI)
            data = json.loads(response_str)
            
            return PhishingAnalysisReport(
                risk_score=data.get("risk_score", 0.0),
                recommendation=data.get("recommendation", "USER_CAUTION"),
                red_flags=data.get("red_flags", []),
                summary=data.get("summary", "Analysis incomplete.")
            )
        except (json.JSONDecodeError, TypeError) as e:
            logger.error(f"Failed to parse LLM response for phishing analysis: {e}")
            return None

# --- Example Usage ---
if __name__ == "__main__":
    import os
    print("=========================================================")
    print("=== AI Phishing Detection Demo (Defensive) 🛡️ ===")
    print("=========================================================")

    # This is a SAFE, FABRICATED text sample of a phishing email.
    SOPHISTICATED_PHISHING_EMAIL = """
    Subject: Urgent Action Required: Security Alert on Your Account

    Dear Valued Customer,

    Our system has detected unusual sign-in activity on your account from an unrecognized device in a different geographical location. For your security, we have temporarily suspended access.

    To restore access and prevent account termination, you must verify your identity immediately by clicking the link below and confirming your credentials.

    Please click here to verify your account: [http://secure-auth-update-center.com/verify]

    This link will expire in 15 minutes. Failure to verify will result in the permanent closure of your account to protect your data.

    Thank you for your prompt attention to this critical security matter.

    Sincerely,
    The Security Team
    """
    
    if not DEVIN_CORE_AVAILABLE or not os.getenv("OPENAI_API_KEY"):
        print("\nERROR: This demo requires the full Devin core and an OPENAI_API_KEY environment variable.")
    else:
        try:
            agent = AIAgent(openai_api_key=os.getenv("OPENAI_API_KEY"))
            analyzer = AIThreatAnalyzer(ai_agent=agent)
            
            print("--- Analyzing a simulated sophisticated phishing email... ---")
            report = analyzer.analyze_text_for_phishing(
                email_body=SOPHISTICATED_PHISHING_EMAIL,
                sender="security@yourbank.com"
            )
            
            if report:
                print("\n--- Phishing Analysis Report ---")
                print(f"  Risk Score:     {report.risk_score:.0%}")
                print(f"  Recommendation: {report.recommendation}")
                print(f"  Summary:        {report.summary}")
                print("  Red Flags Identified:")
                for flag in report.red_flags:
                    print(f"    - {flag}")
            else:
                print("Could not generate an analysis report.")

        except Exception as e:
            logger.error(f"Demo failed to run: {e}", exc_info=True)

    print("\n=========================================================")
    print("=== AI Phishing Detection Demo Complete ===")
    print("=========================================================")
